### ISSUE TITLE
docker events only arriving from the local agent

### ISSUE THREAD

**Issue by blazejosinski** [docker/classicswarm#1937] opened 2016-03-09 15:02 UTC
Hello!
I've a small swarm setup created with `docker machine`: there is one node with swarm master and agent and another one with just swarm agent.

After setting up environment variables, I can start containers on both machines, as expected. However `docker events` only shows information related to containers which are created on the master node. I'm only interested in newly arriving events and I'm not using additional flags (`--since`, `--filter`), so this doesn't seem to be related to [1203](https://github.com/docker/swarm/issues/1203).

I'm using docker version `1.10.2` and swarm version `1.1.0`.
I'm also using token based discovery. Can this problem be caused by it? (as in [1405](https://github.com/docker/swarm/issues/1405))

**Comment by dongluochen** [comment] 2016-03-09 17:56
@blazej0 What's your `DOCKER_HOST` setting? What's the output from `docker info`?

**Comment by blazej0** [comment] 2016-03-10 10:27
$ echo $DOCKER_HOST
    tcp://10.0.4.227:3376
    
    $ docker info
    Containers: 7
     Running: 7
     Paused: 0
     Stopped: 0
    Images: 16
    Role: primary
    Strategy: spread
    Filters: health, port, dependency, affinity, constraint
    Nodes: 2
     swarm-master: 10.0.4.227:2376
      └ Status: Healthy
      └ Containers: 5
      └ Reserved CPUs: 0 / 1
      └ Reserved Memory: 0 B / 2.051 GiB
      └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-74-generic, operatingsystem=Ubuntu 14.04.4 LTS, provider=generic, storagedriver=aus
      └ Error: (none)
      └ UpdatedAt: 2016-03-10T10:20:01Z
     swarm-node-01: 10.0.4.100:2376
      └ Status: Healthy
      └ Containers: 2
      └ Reserved CPUs: 0 / 1
      └ Reserved Memory: 0 B / 1.018 GiB
      └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-74-generic, operatingsystem=Ubuntu 14.04.3 LTS, provider=generic, storagedriver=aus
      └ Error: (none)
      └ UpdatedAt: 2016-03-10T10:20:05Z
    Plugins:
     Volume:
     Network:
    Kernel Version: 3.13.0-74-generic  
    Operating System: linux
    Architecture: amd64
    CPUs: 2
    Total Memory: 3.069 GiB
    Name: swarm-master

And `docker events` only gives me information about containers running on `swarm-master: 10.0.4.227:2376`.

**Comment by dongluochen** [comment] 2016-03-10 18:20
@blazej0 Thanks for the info! `docker events` to swarm manager should aggregate events from all nodes. It doesn't look like #1405 because you have all the nodes listed in `docker info`. 

It may be the aggregation has problem, i.e., `swarm-node-01` events are not collected. Or `swarm-node-01` stops sending events. Can you do a side-by-side tests running both `docker events` (to swarm manager) and `docker -H swarm-node-01:2376 events`? This should tell us where the problem is. Then you can look at logs from the component with error. Docker daemon logs location depends on OS (http://stackoverflow.com/questions/30969435/where-is-the-docker-daemon-log). Swarm manager logs can be inspected with docker `logs` command. If you can provide the logs, it'd help us with the issue.

**Comment by dongluochen** [comment] 2016-03-10 23:04
@blazej0 I suppose you run swarm manager in a container. It's weird no logs since Mar 4th. How often do you see such problem? Can you start manager with debug option like `docker run -d --name=manager swarm -l debug manage ...`? Also swarm v1.1.3 has released you may want to use it.  

When a node is connected to swarm manager, manager starts `monitoring events` from the node. For some reason it seems this monitoring is dropped. If the problem happens with debug enabled, we can focus on text "monitoring events" from `docker logs manager`.

**Comment by blazej0** [comment] 2016-03-14 11:59
A new manager container with debug option worked correctly - events are collected. Previous manager is also working now, after restarting (`docker stop; docker start`). In both cases still using the version 1.1.0.

So the problem is not present at the moment, I'll report if it happens again.
I also hope that restarting manager won't be needed too often.

@dongluochen Thanks for advices on the debugging.

**Comment by ggtools** [comment] 2016-03-24 22:55
I did notice the same issue with the same workaround:

```
Containers: 20
 Running: 18
 Paused: 0
 Stopped: 2
Images: 46
Server Version: swarm/1.1.3
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 node1.domain: xx.xx.xx.xx:2375
  └ Status: Healthy
  └ Containers: 12
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 2.75 GiB / 16.41 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.16.0-62-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-03-24T22:52:22Z
 node2.domain: yy.yy.yy.yy:2375
  └ Status: Healthy
  └ Containers: 8
  └ Reserved CPUs: 0 / 8
  └ Reserved Memory: 0 B / 32.82 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-51-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-03-24T22:51:47Z
Plugins:
 Volume:
 Network:
Kernel Version: 3.16.0-62-generic
Operating System: linux
Architecture: amd64
CPUs: 12
Total Memory: 49.23 GiB
Name: 5afb0c603cb8
```

**Comment by roggithubuab** [comment] 2016-04-12 14:13
I have the same problem.

**Comment by derkork** [comment] 2016-06-20 10:14
I'm having the same issue with Swarm 1.2.2 on Docker 1.10.3. After I enabled debug logging the events suddenly appear on the swarm master. Wonder for how long this will hold.

**Comment by tbouvet** [comment] 2016-07-27 07:10
I have the same issue with Swarm 1.2.3 and Docker 1.11.2
I'm doing the same workaround (stop/start) and it's ok now.
My configuration is 3 masters and 10 nodes. After 5 weeks, up, all swarm events was stopped. I don't know why.
It's a big problem for me because I use traefik (dynamic load balancer) which listens on swarm events.

**Comment by dongluochen** [comment] 2016-07-27 17:54
This maybe related to https://github.com/docker/swarm/issues/2309 that swarm manager missed reconnection from a node. It ends up losing events from a node. 

cc @allencloud.

**Comment by tbouvet** [comment] 2016-07-29 10:11
I don't think it's related to #2309 because the docker engine didn't restart.

**Comment by dongluochen** [comment] 2016-08-01 20:46
I think we need to look at the event connection from swarm node. Usually such problem can be resolved by a heartbeat mechanism. But Docker engine doesn't have heartbeat built-in. We may look how to make it more reliable. 

cc @allencloud.

**Comment by Anvil** [comment] 2016-10-04 09:06
Same issue here. Cannot seem to work around it with swarm 1.2.5 and docker engine 1.12.1.

**Closed** 2020-06-05 17:47 UTC
Labels: area/event, kind/question
