### ISSUE TITLE
Event notifications skipped for containers on restart event due to race condition

### ISSUE THREAD

**Issue by fawadkhaliq** [docker/classicswarm#2495] opened 2016-09-27 17:48 UTC
In a multi-node Docker Swarm cluster, if one of the nodes running Swarm agent is rebooted and any containers which come up before Swarm agents completes syncing up with Swarm Manager are skipped from the Docker events as Swarm Manager is not aware of the start event of the containers after reboot.

Steps to reproduce:
1. Have a cluster running Swarm manager and Swarm agent running on separate nodes
2. Start listening to Docker events via Swarm manager
3. Launch a few containers with "--restart always" flag
4. Reboot the node hosting containers and the swarm agent
5. After the reboot is finished, you will notice containers running, swarm agent running, however, no notification for most of the containers getting relaunched.

Seems like Swarm agent takes a while to sync with Swarm manager and any containers events during that time are lost.

**Comment by michelvocks** [comment] 2016-09-28 06:44
Thanks @fawadkhaliq
This seems to be a duplicate of #2309 and #2108

**Comment by fawadkhaliq** [comment] 2016-09-28 06:48
Thanks for referencing them, @michelvocks . It helps.

**Closed** 2020-06-06 09:51 UTC
Labels: area/event
