### ISSUE TITLE
`docker ps --filter ancestor=...` includes all images

### ISSUE THREAD

**Issue by jpetazzo** [docker/classicswarm#1716] opened 2016-01-30 22:04 UTC
**What I have:**

5 nodes cluster running Swarm 1.1.0-rc2 and Engine 1.9.1.

One one node, I'm running 4 containers:
- swarm agent
- swarm manager
- `docker run -dti alpine sh`
- `docker run -dti ubuntu sh`

**What I do:**

```
docker ps --filter ancestor=ubuntu
```

**What I expect to see:**

Just the Ubuntu container (that's what I see if I run the command vs my single node):

```
docker@node1 ~: docker ps --filter ancestor=ubuntu
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
eac3f738eabb        ubuntu              "bash"              4 minutes ago       Up 4 minutes                            fervent_shaw
```

**What I see instead:**

All running containers (if I add `-a`, I see all containers)

```
docker@node1 ~: docker ps --filter ancestor=ubuntu
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
eac3f738eabb        ubuntu              "bash"              5 minutes ago       Up 5 minutes                            node1/fervent_shaw
d31cf173703a        alpine              "sh"                6 minutes ago       Up 6 minutes                            node1/desperate_fermi
```

**Notes:**

I'm linking to #1700 since it looks _vaguely_ similar.

If somebody from the Docker team wants to look, I can give them access to a pre-configured cluster exhibiting the issue.

**Comment by abronan** [comment] 2016-01-31 00:21
Thanks @jpetazzo! I think it indeed looks like a duplicate of #1700 but we'll keep it open for now as this adds some insights and details to the original issue.

/cc @dongluochen @vieux

**Comment by jpetazzo** [comment] 2016-03-02 09:54
This is still the case with 1.1.3-rc2, by the way.

**Comment by EvanMcClure** [comment] 2016-03-03 02:42
:+1:

I believe this bug is _not_ related to #1700.

**Comment by nishanttotla** [comment] 2016-03-03 02:45
I think we might have a better chance of supporting this once #1879 is through. Hopefully that can happen by the 1.2 release!

**Comment by RichardJECooke** [comment] 2016-05-16 13:37
Sorry to bother yall, but could this bug be causing my issue, or am I just making a mistake in my filter?
`http://stackoverflow.com/questions/37255264/why-does-docker-filter-ancestor-imagename-find-the-wrong-container`

**Comment by fbuecklers** [comment] 2017-11-21 14:01
Any updates on this issue?

**Comment by alexey-igrychev** [comment] 2018-08-17 14:12
I have similar problem with ancestor filter:
```bash
$ docker run --name ubuntu_container ubuntu
$ docker commit ubuntu_container test
sha256:873893563d49c46062135247f2ca23115453ac59eaa42c40e65853823b56ad4c
$ docker run --name test_container test
$ docker ps -a --filter=ancestor=test
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                              PORTS               NAMES
ab26278b1607        test                "/bin/bash"         1 second ago        Exited (0) Less than a second ago                       test_container
$ docker ps -a --filter=ancestor=ubuntu
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                              PORTS               NAMES
ab26278b1607        test                "/bin/bash"         1 second ago        Exited (0) Less than a second ago                       test_container
450f14f1ce5c        ubuntu              "/bin/bash"         2 seconds ago       Exited (0) 1 second ago                                 ubuntu_container
```

**Closed** 2020-06-05 17:41 UTC
Labels: area/API, kind/bug
